---
site_config:
  ntp: 
    - "157.82.226.81"
  munin_cidr: "10.100.200.0/24"
  cron_apt_hour: "4"
  dnsmasq:
    site: "ipmu"
  exim4_smarthost: "10.100.200.2"
  ldap_uri: "ldap://10.100.200.2/"
  ldap_base: "dc=shell,dc=pfs,dc=ipmu,dc=jp"
  nfs:
    common:
      - source: "10.100.200.4:/data1"
        target: "/data1"
      - source: "10.100.200.3:/server/home"
        target: "/home"
  virt:
    nfsdisk: "10.100.200.3:/virt"
    pki:
      local: "/virt/pki/"

