---
site_config:
  ntp: 
    - "157.82.226.81"
  munin_cidr: "10.100.200.0/24"
  cron_apt_hour: "4"
  dnsmasq:
    site: "ipmu"
  exim4_smarthost: "10.100.200.2"
  ldap_uri: "ldap://10.100.200.2/"
  ldap_base: "dc=shell,dc=pfs,dc=ipmu,dc=jp"
  nfs:
    common:
      - source: "10.100.200.4:/data1"
        target: "/data1"
      - source: "10.100.200.3:/server/home"
        target: "/home"
  system_accounts:
    groups:
      - gname: "libvirt-qemu"
        gid: 200
      - gname: "munin"
        gid: 201
      - gname: "mysql"
        gid: 202
      - gname: "postgres"
        gid: 203
      - gname: "kvm"
        gid: 204
    users:
      - uname: "libvirt-qemu"
        uid: 200
        home: "/var/lib/libvirt"
        group: "libvirt-qemu"
        groups: "kvm"
      - uname: "munin"
        uid: 201
        home: "/var/lib/munin"
        group: "munin"
      - uname: "mysql"
        uid: 202
        home: "/var/lib/mysql"
        group: "mysql"
      - uname: "postgres"
        uid: 203
        home: "/var/lib/postgres"
        group: "postgres"
        shell: "/bin/bash"
  virt:
    nfsdisk: "10.100.200.3:/virt"
    pki:
      local: "/virt/pki/"

