---
- name: restart postfix
  systemd:
    name: postfix.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes
- name: restart iptables-persistent
  systemd:
    name: iptables-persistent.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes

