---
- name: system wide common package
  become: yes
  apt: >
    name={{ item }}
    state=present
  with_items:
    - screen
    - vim-nox
    - vim-addon-manager
    - vim-scripts
    - tcsh
    - zsh
