---
- name: Install required pip3 packages
  become: yes
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items:
    - astropy
    - matplotlib
    - scipy
    - twisted
- name: Create target directory
  become: yes
  file:
    path: "/data/ics/{{ ansible_hostname }}/devel/"
    state: directory
    mode: 0755
    owner: "pfs"
    group: "pfs"
- name: Clone EUPS
  git:
    repo: "https://github.com/RobertLuptonTheGood/eups.git"
    dest: "/data/ics/{{ ansible_hostname }}/devel/eups/"
    update: yes
    force: yes
    version: "{{ eups.version }}"
  register: task_git_clone
- name: Configure EUPS install
  command: ./configure --with-eups=/data/ics/{{ ansible_hostname }}/products --prefix=/data/ics/{{ ansible_hostname }}/products/eups/{{ eups.version }} chdir=/data/ics/{{ ansible_hostname }}/devel/eups/
  when: task_git_clone.changed
- name: Build EUPS
  make:
    chdir: "/data/ics/{{ ansible_hostname }}/devel/eups/"
    target: install
  when: task_git_clone.changed
- name: Symlink EUPS default directory
  file:
    src: "/data/ics/{{ ansible_hostname }}/products/eups/{{ eups.version }}"
    dest: "/data/ics/{{ ansible_hostname }}/products/eups/default"
    state: link
  when: task_git_clone.changed
- name: Symlink EUPS setups at home
  file:
    src: "/data/ics/{{ ansible_hostname }}/products/eups/default/bin/setups.sh"
    dest: "~/setups.sh"
    state: link
- name: Add ~/bin/ directory
  file:
    path: ~/bin/
    state: directory
    mode: 0755
- name: Symlink python as python3 at home
  file:
    src: /usr/bin/python3
    dest: ~/bin/python
    owner: pfs
    group: pfs
    state: link
    mode: 0755
- name: Add export to .bashrc
  lineinfile:
    dest: "~/.bashrc"
    regexp: "^export {{ item.name }}="
    line: "export {{ item.name }}={{ item.value }}"
  with_items:
    - name: "ICS_ROOT"
      value: "/data/ics/{{ ansible_hostname }}/"
    - name: "ICS_MHS_ROOT"
      value: "/data/ics/{{ ansible_hostname }}/"
    - name: "ICS_DEVEL_ROOT"
      value: "/data/ics/{{ ansible_hostname }}/devel/"
    - name: "PATH"
      value: "~/bin/:${PATH}"

