---
#
# change source list and do dist-upgrade
#

- name: copy source.list
  hosts: all
  remote_user: pfs
  become: true
  serial: 1 # one host at a time
  any_errors_fatal: true
  max_fail_percentage: 0

  handlers:
    - name: show os version
      shell: lsb_release -da
      register: shell_result
      listen: "show os"

    - debug:
       var: shell_result.stdout_lines


  tasks: # tasks are done in order
    - name: APT | Ensure the sources list in /etc/apt/sources.list is updated
      template:
        src:  sources.list.stretch
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: 0644

    # do an "apt-get update", to ensure latest package lists
    - name: apt-get update
      apt:
        update-cache: yes
      changed_when: 0
      become: yes
      become_method: sudo
      notify: "show os"

    # do an "apt-get dist-upgrade", to ensure latest package lists
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
      become: yes
      become_method: sudo