---
- name: restart ipmi-exporter
  systemd:
    name: ipmi-exporter.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes
- name: restart prometheus-mysqld-exporter
  systemd:
    name: prometheus-mysqld-exporter.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes
- name: restart prometheus-postgres-exporter
  systemd:
    name: prometheus-postgres-exporter.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes
- name: restart hpraid-exporter
  systemd:
    name: hpraid_exporter.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes

