---
- hosts: all
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - system-accounts
    - { role: packages, packages: "{{ site_config.packages.sitewide }}" }
    - cron-apt
    - ntp
    - munin-node
    - exim4

#    - ldap
#    - { role: nfs, nfsv3_target: "{{ site_config.nfs.common }}" }

