---
- hosts: all
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - system-accounts
    - iptables
    - { role: packages, packages: "{{ site_config.packages.sitewide }}" }
    - cron-apt
    - { role: ntp, when: "server_ntp is undefined" }
    - { role: rsyslog-client, when: "server_rsyslog is undefined" }
    - { role: exim4, when: "server_smarthost is undefined" }

- hosts: ldap
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - ldap
- hosts: server
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - { role: nfs-client, when: "nfsv3_target is defined" }
    - { role: ntp-server, when: "server_ntp is defined" }
    - { role: rsyslog-server, when: "server_rsyslog is defined" }
- hosts: gateway
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - ssh-gateway

- hosts: virt-host
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - virt

- hosts: actor
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - eups

- hosts: hwraid
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - hwraid
- hosts: fc-nfs
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - iscsi
    - nfs-server
- hosts: landfill
  vars_files:
    - "group_vars/site_{{ ansible_dns.domain }}.yml"
  roles:
    - boot-aptupdate

