---
- name: Add kernel module for ipmi exporter
  become: yes
  lineinfile:
    dest: /etc/modules
    line: "{{ item }}"
  with_items:
    - ipmi_si
    - ipmi_devintf
  when: prometheus_exporters_ipmi is defined
  notify: restart ipmi-exporter
- name: Load kernel module for ipmi exporter
  become: yes
  shell: modprobe {{ item }}
  with_items:
    - ipmi_si
    - ipmi_devintf
  when: prometheus_exporters_ipmi is defined
  changed_when: False
  notify: restart ipmi-exporter

- name: Check snmp_exporter binary
  stat: path="{{ env_gopath }}/bin/snmp_exporter"
  when: prometheus_exporters_snmp is defined
  delegate_to: 127.0.0.1
  register: prometheus_exporters_snmp_file
- name: Create directory for snmp exporter binary
  file:
    path: "~/snmp_exporter/"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    mode: 0755
  when: prometheus_exporters_snmp_file.stat.md5 is defined
- name: Copy binary to target
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - src: "{{ env_gopath }}/bin/snmp_exporter"
      dest: "~/snmp_exporter/snmp_exporter"
  when: prometheus_exporters_snmp_file.stat.md5 is defined
- name: Copy invoke script for snmp exporter
  template:
    src: "{{ item }}"
    dest: "~/{{ item }}"
    mode: 0755
  with_items:
    - snmp_exporter.sh
  when: prometheus_exporters_snmp_file.stat.md5 is defined
- name: Copy snmp definition for snmp exporter
  template:
    src: "{{ item }}"
    dest: "~/snmp_exporter/{{ item }}"
    mode: 0644
  with_items:
    - snmp_orig.yml
    - snmp_ushaups.yml
  when: prometheus_exporters_snmp_file.stat.md5 is defined
- name: Add @reboot cron job for snmp exporter
  cron:
    special_time: reboot
    job: "~/snmp_exporter.sh"
    name: snmp_exporter_on_boot
  when: prometheus_exporters_snmp_file.stat.md5 is defined

- name: Add database connection for mysql exporter
  become: yes
  lineinfile:
    dest: /etc/default/prometheus-mysqld-exporter
    regexp: "^{{ item.key }}"
    line: "{{ item.value }}"
    mode: '0600'
  with_items:
    - key: "DATA_SOURCE_NAME"
      value: "DATA_SOURCE_NAME=\"{{ prometheus_exporters_mysql_account }}@({{ site_config.prometheus_exporter.mysql.host }})/mysql\""
  when: prometheus_exporters_mysql is defined and prometheus_exporters_mysql_account != ""
  notify: restart prometheus-mysqld-exporter

- name: Add database connection for pgsql exporter
  become: yes
  lineinfile:
    dest: /etc/default/prometheus-postgres-exporter
    regexp: "^{{ item.key }}"
    line: "{{ item.key }}='{{ item.value }}'"
  with_items:
    - key: "DATA_SOURCE_NAME"
      value: "postgresql://{{ prometheus_exporters_pgsql_account }}@{{ site_config.prometheus_exporter.pgsql.host }}/postgres"
    - key: "ARGS"
      value: "\\\n"
  when: prometheus_exporters_pgsql is defined and prometheus_exporters_pgsql_account != ""
  notify: restart prometheus-postgres-exporter
- name: Add service configuration for pgsql exporter
  become: yes
  lineinfile:
    dest: /etc/default/prometheus-postgres-exporter
    line: "{{ item }}"
    insertafter: "^ARGS='"
  with_items:
    - "--extend.query-path=\"/etc/default/prometheus-postgres-exporter-queries.yaml\" \\"
  when: prometheus_exporters_pgsql is defined
  notify: restart prometheus-postgres-exporter
- name: Add pgsql query definition yaml
  become: yes
  template:
    src: "{{ item }}"
    dest: "/etc/default/{{ item }}"
    mode: 0644
  with_items:
    - prometheus-postgres-exporter-queries.yaml
  when: prometheus_exporters_pgsql is defined
  notify: restart prometheus-postgres-exporter

- name: Check elasticsearch_exporter binary
  stat: path="{{ env_gopath }}/bin/elasticsearch_exporter"
  when: prometheus_exporters_es is defined
  delegate_to: 127.0.0.1
  register: prometheus_exporters_es_file
- name: Copy binary to target
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - src: "{{ env_gopath }}/bin/elasticsearch_exporter"
      dest: "~/elasticsearch_exporter"
  when: prometheus_exporters_es_file.stat.md5 is defined
- name: Copy invoke script for elasticsearch exporter
  template:
    src: "{{ item }}"
    dest: "~/{{ item }}"
    mode: 0755
  with_items:
    - elasticsearch_exporter.sh
  when: prometheus_exporters_es_file.stat.md5 is defined
- name: Add @reboot cron job for elasticsearch exporter
  cron:
    special_time: reboot
    job: "~/elasticsearch_exporter.sh"
    name: es_exporter_on_boot
  when: prometheus_exporters_es_file.stat.md5 is defined

- name: Include exporter tasks as hpraid_exporter
  include: exporter.yml
  vars:
    exporter:
      name: hpraid_exporter
      opt_args:
        - "-cmd /usr/sbin/hpacucli"
  when: hwraid_target_hp is defined
  notify: restart hpraid-exporter

