---
- name: Make mysql data directory existing
  become: yes
  file:
    path: /services/mysql/
    state: directory
    owner: mysql
    mode: 0755
- name: Configure mysql server
  become: yes
  ini_file:
    dest: "/etc/mysql/mariadb.conf.d/50-server.cnf"
    section: "mysqld"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - option: "bind-address"
      value: "0.0.0.0"
    - option: slow_query_log_file
      value: /var/log/mysql/mariadb-slow.log
    - option: long_query_time
      value: 1
    - option: datadir
      value: /services/mysql/
  notify: restart mysql

