---
- name: nslcd configuration
  become: yes
  lineinfile: >
    dest=/etc/nslcd.conf
    owner=root group=nslcd mode=0640 backup=no
    regexp="{{ item.regexp }}"
    insertafter="{{ item.insertafter }}"
    line="{{ item.line }}"
  with_items: 
    - regexp: '^uri'
      insertafter: '^#uri'
      line: "uri {{ site_config.ldap.uri }}"
    - regexp: '^base'
      insertafter: '^#base'
      line: "base {{ site_config.ldap.base }}"
  notify: restart nslcd
- name: nsswitch configuration
  become: yes
  lineinfile: >
    dest=/etc/nsswitch.conf
    owner=root group=root mode=0644 backup=no
    regexp="^{{ item }}"
    line="{{ item }}: compat ldap"
  with_items: 
    - "passwd"
    - "group"
    - "shadow"
  notify: restart nslcd
- name: configure backup for slapd
  become: yes
  cron:
    minute: 5
    hour: 0
    job: "{{ site_config.system_dirs.git_clone }}/{{ item.url }}/admin-script/ldap-backup.sh"
    cron_file: "/etc/crontab"
    user: root
    name: backup-ldap
  when: install_backup_ldap is defined

