---
- name: Configure sysctl
  become: yes
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
- name: Configure iptables
  become: yes
  vars:
    mask: "{{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.netmask }}"
  lineinfile:
    dest: "/etc/iptables/rules.v4"
    line: "{{ item.line }}"
    insertafter: "^# ANSIBLE_ROLE_{{ item.pos }}_PLACE"
  with_items:
    - line: "-A POSTROUTING -s {{ mask }} -j LOG --log-prefix \"{{ site_config.nat_route.prefix | default('PF: ') }}\" --log-level={{ site_config.nat_route.loglevel | default('info') }} --log-tcp-sequence"
      pos: "NAT"
    - line: "-A POSTROUTING -s {{ mask }} -j MASQUERADE"
      pos: "NAT"
    - line: "-A FORWARD -s {{ mask }} -j ACCEPT"
      pos: "FILTER"
  notify: restart iptables-persistent

