---
- name: rsyslog package
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - rsyslog
- name: Enable imudp and imtcp
  become: yes
  lineinfile:
    dest: /etc/rsyslog.conf
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  notify: restart rsyslog
  with_items:
    - line: "module(load=\"imudp\")"
      regexp: "^module.*imudp"
    - line: "input(type=\"imudp\" port=\"514\" ruleset=\"extinput\")"
      regexp: "^input.*imudp"
    - line: "module(load=\"imtcp\")"
      regexp: "^module.*imtdp"
    - line: "input(type=\"imtcp\" port=\"514\" ruleset=\"extinput\")"
      regexp: "^input.*imtdp"
- name: Copy syslog line handler configuration for repush to logstash
  become: yes
  template:
    src: "{{ item }}"
    dest: "/etc/rsyslog.d/{{ item }}"
    mode: 0644
  notify: restart rsyslog
  with_items:
    - 60-output.conf
  when: site_config.rsyslog.repush is defined
- name: Copy syslog line handler configuration via omfile
  become: yes
  template:
    src: "{{ item }}"
    dest: "/etc/rsyslog.d/{{ item }}"
    mode: 0644
  notify: restart rsyslog
  with_items:
    - 60-omfile.conf
  when: site_config.rsyslog.omfile is defined

