---
- name: Install iscsiadm
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - open-iscsi
    - multipath-tools
    - multipath-tools-boot
- name: Configure iscsiadm startup
  become: yes
  lineinfile:
    dest: /etc/iscsi/iscsid.conf
    regexp: "^node.startup ="
    line: "node.startup = automatic"
- name: Exec connection
  command: "{{ item }}"
  become: yes
  with_items:
    - "iscsiadm -m discovery"
    - "iscsiadm -m node --login"

