---
- name: Add package cloud apt-key
  become: yes
  apt_key:
    url: "https://packagecloud.io/{{ packagecloud.target_id }}/gpgkey"
    state: present
- name: Add package cloud apt line
  become: yes
  apt_repository:
    repo: "deb https://packagecloud.io/{{ packagecloud.target_id }}/debian/ {{ ansible_lsb.codename }} main"
    state: present
    update_cache: yes

